---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update and Upgrade
    yum:
      update_cache: yes
      upgrade: 'yes'

  tasks:
    - name: Base applications installation
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - nc
        - java-1.8.0-openjdk
        - telnet
        - docker
    
    - name: Adding jenkins.repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
  
    - name: Importing Jenkins Key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Jenkins instalation
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Systemctl enable Docker 
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Adding the "ec2-user" to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Systemctl restart docker
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker

    - name: Docker-Compose instalation
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: 30 seconds Sleep
      wait_for: timeout=30

    - name: Catching "initialAdminPassword"
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result
  
    - name: Printing Jenkins init password
      debug:
        var: result.stdout