---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update and Upgrade
    yum:
      name: '*'
      state: latest

  tasks:
    - name: Base applications installation
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - nc
        - telnet
        - java-1.8.0-openjdk
    
    - name: Adding jenkins.repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
  
    - name: Importing Jenkins Key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Jenkins instalation
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: 10 seconds Sleep
      wait_for: timeout=10

    - name: Catching "initialAdminPassword"
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result
  
    - name: Printing Jenkins init password
      debug:
        var: result.stdout